name: Java CI with Gradle

# Run this workflow on every push to develop and feature/* branches, and on pull requests to develop
on:
  push:
    branches:
      - develop
      - feature/*
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up JDK 11 (or higher if you want to change)
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    # Cache Gradle dependencies to speed up future builds
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: ${{ runner.os }}-gradle

    # Run the Gradle build
    - name: Build with Gradle
      run: ./gradlew build

    # Run the JUnit tests
    - name: Run tests
      run: ./gradlew test
 
